name: EC2 Deploy

on:
  workflow_dispatch:
# Define environment variables  
env:  
  AWS_REGION: ap-southeast-2
  UPDATE_SCRIPT: .github/workflows/ec2_update.sh
  EC2_IP: 3.107.160.80

jobs:
  deploy:
    name: Deploy Docker Images to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup SSH and Deploy
      run: |
        # Install dependencies
        sudo apt-get update -y
        sudo apt-get install -y openssh-client git

        # Setup SSH
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Write private key with proper formatting
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519.pem
        chmod 600 ~/.ssh/id_ed25519.pem
        
        # Start SSH agent
        eval $(ssh-agent -s)
        
        # Add key to agent with retry
        for i in {1..3}; do
          if ssh-add ~/.ssh/id_ed25519.pem; then
            break
          fi
          sleep 2
          echo "Retrying to add SSH key..."
        done
        
        # Configure known hosts
        ssh-keyscan ${{ env.EC2_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        
        # Copy update script
        scp -o StrictHostKeyChecking=no -r ${{ env.UPDATE_SCRIPT }} ec2-user@${{ env.EC2_IP }}:/home/ec2-user/
        
        # Execute remote commands
        ssh -o StrictHostKeyChecking=no ec2-user@${{ env.EC2_IP }} << 'EOF'
          export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          chmod +x /home/ec2-user/ec2_update.sh
          /home/ec2-user/ec2_update.sh
        EOF
