name: EC2 Deploy

on:
  workflow_dispatch:
env:
  AWS_REGION: ap-southeast-2
  UPDATE_SCRIPT: .github/workflows/ec2_update.sh
  EC2_IP: 54.252.219.100
  SSH_USER: ec2-user

jobs:
  deploy:
    name: Deploy Docker Images to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup SSH Connection
      id: ssh-setup
      run: |
        # Install dependencies
        sudo apt-get update -y
        sudo apt-get install -y openssh-client git
        
        # Create SSH directory
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Write the private key with proper formatting
        {
          echo "-----BEGIN OPENSSH PRIVATE KEY-----"
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | \
            sed -e '/-----BEGIN OPENSSH PRIVATE KEY-----/d' \
                -e '/-----END OPENSSH PRIVATE KEY-----/d' \
                -e 's/^[[:space:]]*//' \
                -e 's/[[:space:]]*$//'
          echo "-----END OPENSSH PRIVATE KEY-----"
        } > ~/.ssh/id_ed25519
        
        # Set strict permissions
        chmod 600 ~/.ssh/id_ed25519
        
        # Verify key format
        if ! ssh-keygen -l -f ~/.ssh/id_ed25519 >/dev/null; then
          echo "::error::Invalid SSH Key Format"
          exit 1
        fi
        
        # Setup SSH agent
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_ed25519
        
        # Add EC2 to known hosts
        ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Test SSH Connection
      if: steps.ssh-setup.outcome == 'success'
      run: |
        ssh -o StrictHostKeyChecking=no -T ${{ env.SSH_USER }}@${{ env.EC2_IP }} "echo 'SSH connection successful'"

    - name: Deploy to EC2
      if: steps.ssh-setup.outcome == 'success'
      run: |
        # Transfer update script
        scp -o StrictHostKeyChecking=no ${{ env.UPDATE_SCRIPT }} ${{ env.SSH_USER }}@${{ env.EC2_IP }}:~/ || {
          echo "::error::Failed to transfer script"
          exit 1
        }
        
        # Execute remote commands
        ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.EC2_IP }} << 'DEPLOY_EOF'
          set -e
          export OPENAI_API_KEY=$OPENAI_API_KEY
          chmod +x ~/ec2_update.sh
          
          # Docker setup
          if ! command -v docker &>/dev/null; then
            sudo yum install -y docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER
          fi
          
          # Execute update script
          sudo ~/ec2_update.sh
        DEPLOY_EOF
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
