name: EC2 Deploy

on:
  workflow_dispatch:
env:
  AWS_REGION: ap-southeast-2
  UPDATE_SCRIPT: .github/workflows/ec2_update.sh
  EC2_IP: 54.252.219.100
  SSH_USER: ec2-user

jobs:
  deploy:
    name: Deploy Docker Images to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup SSH Connection
      id: ssh-setup
      run: |
        # Install dependencies
        sudo apt-get update -y
        sudo apt-get install -y openssh-client git
        
        # Create SSH directory
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        
        # Write the private key with proper formatting
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        
        # Clean up the key file
        sed -i '/^-----BEGIN OPENSSH PRIVATE KEY-----$/,/^-----END OPENSSH PRIVATE KEY-----$/!d' ~/.ssh/id_ed25519
        sed -i '/^$/d' ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        
        # Verify key format
        echo "=== Key Verification ==="
        if ! ssh-keygen -l -f ~/.ssh/id_ed25519 >/dev/null 2>&1; then
          echo "::error::Invalid SSH Key Format"
          echo "Key content:"
          cat ~/.ssh/id_ed25519
          exit 1
        fi
        
        # Setup SSH agent
        eval $(ssh-agent -s)
        if ! ssh-add ~/.ssh/id_ed25519; then
          echo "::error::Failed to add SSH key"
          exit 1
        fi
        
        # Add EC2 to known hosts
        ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts

    - name: Deploy to EC2
      if: steps.ssh-setup.outcome == 'success'
      run: |
        # Transfer update script with retry
        max_retries=3
        for i in $(seq 1 $max_retries); do
          if scp -o StrictHostKeyChecking=no ${{ env.UPDATE_SCRIPT }} ${{ env.SSH_USER }}@${{ env.EC2_IP }}:~/; then
            break
          else
            echo "Attempt $i failed, retrying..."
            sleep 5
            if [ $i -eq $max_retries ]; then
              echo "::error::Failed to transfer script after $max_retries attempts"
              exit 1
            fi
          fi
        done
        
        # Execute remote commands
        ssh -o StrictHostKeyChecking=no ${{ env.SSH_USER }}@${{ env.EC2_IP }} << 'DEPLOY_EOF'
          set -ex
          export OPENAI_API_KEY=$OPENAI_API_KEY
          chmod +x ~/ec2_update.sh
          
          # Ensure Docker is available
          if ! command -v docker &>/dev/null; then
            sudo yum install -y docker
            sudo systemctl start docker
            sudo usermod -aG docker $USER
          fi
          
          # Temporary permission fix if needed
          if [ ! -w /var/run/docker.sock ]; then
            sudo chmod 666 /var/run/docker.sock || true
          fi
          
          # Execute update script
          sudo ~/ec2_update.sh
        DEPLOY_EOF
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
