- name: Create Private Key File
  run: |
    # 安装依赖，如果必要
    which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )
    
    # 启动 ssh-agent
    eval $(ssh-agent -s)
    
    # 创建 SSH 目录并设置权限
    mkdir -p ~/.ssh
    chmod 700 ~/.ssh
    
    # 将私钥写入文件
    echo "${{ secrets.AWS_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_ed
    chmod 600 ~/.ssh/id_ed
    
    # 检查私钥格式
    echo "=== Checking SSH Key ==="
    ssh-keygen -l -f ~/.ssh/id_ed || { echo "::error::Invalid SSH Key Format"; exit 1; }
    
    # 将私钥添加到 ssh-agent
    ssh-add ~/.ssh/id_ed
    
    # 检查 ssh-agent 中的密钥
    echo "=== Listing SSH Keys ==="
    ssh-add -l
    
    # 创建 known_hosts 文件并添加 EC2 主机密钥
    touch ~/.ssh/known_hosts
    chmod 600 ~/.ssh/known_hosts
    ssh-keyscan -H 13.236.165.153 >> ~/.ssh/known_hosts
    
    # 将更新脚本传输到 EC2
    scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed -r .github/workflows/ec2_update.sh ec2-user@13.236.165.153:/home/ec2-user/
    
    # 在 EC2 上执行脚本
    ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed ec2-user@13.236.165.153 << 'EOF'
      export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
      chmod +x /home/ec2-user/ec2_update.sh
      /home/ec2-user/ec2_update.sh
    EOF
