name: EC2 Construct 
 
on: 
  workflow_dispatch: 
 
env: 
  AWS_REGION: ap-southeast-2 
 
jobs: 
  terraform: 
    name: Apply Terraform configuration 
    runs-on: ubuntu-latest 
    defaults: 
      run: 
        working-directory: ./ec2/ 
 
    steps: 
      - name: Checkout terraform code 
        uses: actions/checkout@v4
 
      - name: Set up Terraform 
        uses: hashicorp/setup-terraform@v2 
        with: 
          terraform_version: 1.0.0 
 
      - name: Configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ${{ env.AWS_REGION }} 
 
      - name: Initialize Terraform 
        run: terraform init 
 
      - name: Terraform Plan 
        run: terraform plan 
 
      - name: Terraform Apply 
        if: github.ref == 'refs/heads/main' 
        run: terraform apply -auto-approve 
 
      - name: Get EC2 IP 
        run: terraform output -raw instance_public_ip > ip.txt 
 
      - name: Upload IP File 
        uses: actions/upload-artifact@v3 
        with: 
          name: ip-file 
          path: ip.txt 
 
  build-image: 
    name: AWS ECR preparation 
    needs: terraform 
    permissions: 
      packages: write 
      contents: read 
    uses:  QiushiZhou/resumeAPI/.github/workflows/build-push.yml@main
    with:
      VITE_SERVER_HOST: "http://${{ steps.get_ip.outputs.ip }}"
      DOCKER_COMPOSE_FILE: ./resumeAPI/docker-compose.yml 
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
    # steps: 
    #   - name: Checkout Terraform Repo 
    #     uses: actions/checkout@v4
 
    #   - name: Checkout ResumeAPI Repo 
    #     uses: actions/checkout@v4
    #     with: 
    #       repository: QiushiZhou/resumeAPI 
    #       path: resumeAPI 
 
    #   - name: Download IP File 
    #     uses: actions/download-artifact@v3 
    #     with: 
    #       name: ip-file 
    #       path: . 
          
    #   - name: Read IP File
    #     id: get_ip
    #     run: echo "ip=$(cat ip.txt)" >> $GITHUB_OUTPUT
 
    #   - name: Invoke Build and Push 
    #     uses: QiushiZhou/resumeAPI/.github/workflows/build-push.yml@main 
    #     with: 
    #       VITE_SERVER_HOST: "http://${{ steps.get_ip.outputs.ip }}"
    #       DOCKER_COMPOSE_FILE: ./resumeAPI/docker-compose.yml 
    #     env: 
    #       AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} 
    #       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
